AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sdk-example

  Sample SAM Template for aws-sdk-example

Globals:
  Function:
    Timeout: 20

Resources:
  GetDogFactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dogfacts
      Handler: io.chaotics.examples.GetDogHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /fact
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DogFactsTable

  CreateDogFactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dogfacts
      Handler: io.chaotics.examples.CreateDogHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Environment:
        Variables:
          OVERRIDE_URL: https://api.chaotics.io/endpoint?apiId=a50eb35e-b89d-4a06-8dd7-9b150a0036cf
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /fact
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DogFactsTable

  DogFactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Dogs
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  DogFactFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fact/"
